name: Auto Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # triggers deployment on every push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production --base-href "https://AlbertWilliamsW.github.io/albert-bio-data-app/"

      # 5️⃣ Deploy using angular-cli-ghpages
      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/albert-bio-data-app/browser --force
